spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: xxxxxx 
  data:
    redis:
      host: localhost
      port: 6379
      password: 129496
mybatis:
  mapper-locations: classpath*:/mapper/*.xml

# 详见：https://doc.xiaominfo.com/，访问地址：http://ip:port/doc.html
knife4j:
  enable: true
  setting:
    language: zh_cn
